project:
  type: website
execute:
  cache: false    # inline results conflict with cache use
  freeze: auto
github:
  owner: palday
  repo: economics2024

website:
  title: "Mixed Effects Models in Julia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 01-intro.qmd
        text: MixedModels.jl
      - href: 02-plotting.qmd
        text: Visualization
      - href: 03-extensions.qmd
        text: Extension Packages
      - href: 04-bootstrap.qmd
        text: Bootstrap
      - href: 99-wilkinson-notation.md
        text: Formula Syntax
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    author: 
      - name: Phillip Alday
        email: me@phillipalday.com
        orcid: 0000-0002-9984-5745
        
execute-dir: project
engine: julia
julia:
  exeflags: ["--project"]
